apiVersion: apps/v1
kind: Deployment
metadata:
  name: mizantestwebapp
  #labels:
   # app: testwebapp 
spec:
  # modify replicas according to your case
  replicas: 3  
  selector:
    matchLabels:
      app:  testwebapp
  template:
    metadata:      
      labels:
        app: testwebapp
    spec:
      containers:
        - name: mizantestwebapp
          image: mizanregistry.azurecr.io/mizantestwebapp:1
          resources:
              limits:
                memory: "128Mi"
                cpu: "500m"
          ports:
            - containerPort: 8080
