apiVersion: v1
kind: Pod
metadata:
  name: mizantestwebapp-release-v2
  labels:
    app: mizantestwebapp
    release: v2
spec:
  containers:
  - name: mizantestwebapp
    image: mizanregistry.azurecr.io/mizantestwebapp:2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080